<?php

/**
 * @file
 * Contains block_api_task.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_api_task_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_api_task module.
    case 'help.page.block_api_task':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Block API module task') . '</p>';
      return $output;

    default:
  }
}
