<?php

/**
 * @file
 * Contains configured_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function configured_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the configured_entity module.
    case 'help.page.configured_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configured Entity') . '</p>';
      return $output;

    default:
  }
}
